### ISSUE TITLE
Cannot build

### ISSUE THREAD

**Issue by Erdemes** [Erdemes/modlist#1]
Hello @veteran29, I’ve downloaded your source code and tried to build it with the npm commands but the built index.html doesn’t work. I want to use your awesome work in our php site and I don’t exactly know if it is possible I don’t have enough knowledge, can you help me?

**Comment by veteran29** [comment]
Are you using the index.html from the dist folder? I've just built it and it works fine, also the same code is running on production. Make sure you're hosting it properly via web serwer and not opening via browser and relative paths to assets are correct.

**Comment by Erdemes** [comment]
When I build the source code it creates static folder and index.html file in the dist folder where there are several .js and .js.map files in the static folder. 
I’m uploading this dist folder to my web server. I open up the page by typing the folder url in my web server and it gives me a blank page only with a title specified in index.html

**Comment by veteran29** [comment]
Then everything build correctly most likely, verify your browser debug console, it's a matter of correctly setting up the relative paths  so the JS files can be loaded.

**Comment by Erdemes** [comment]
I just found out that static folder had to be placed in the root folder. I was placing all of them in root/modlist folder. Now everything works as intended. Thank you for this awesome work and help!
